### ISSUE TITLE
Add Favicon ico.

### ISSUE THREAD

**Issue by Shashankfeeling** [btechtards/btechtards.github.io#4]
Please Assign me this for hacktoberfest.

**Comment by sajalkmr** [comment]
You can add favicon, make one from the logo on the account

**Comment by Shashankfeeling** [comment]
Added the favicon Icon. Please check the PR if its correct then merge it.
![image](https://user-images.githubusercontent.com/87827112/195948750-21a74abd-f8a1-4877-929b-fc0a5b7eb7c5.png)

**Comment by sajalkmr** [comment]
Use this for favicon- https://imgur.com/a/ihvWiRk

**Comment by Shashankfeeling** [comment]
Okay, now check i corrected my mistake.

**Comment by sajalkmr** [comment]
Merged
